linear cross validation
meyer-lab/DE-learning pull request #129
Opened 2021-08-09 17:36 UTC by AshlynPowell

Added linear option to impute function

2021-08-10 21:24 UTC, Farnazmdi commented on de/fitting.py
> +                w, eta = reshapeParams(xx, data.shape[0])
@AshlynPowell I think the `prediction` used here comes from the same dataset used for training. I think you should use the `model.predict()` on the test set. It probably requires some changes to the `Fitting()` function.

2021-08-16 17:35 UTC, Farnazmdi commented
@AshlynPowell it appeared the `SSE()` function was not being used so I removed it.
Let me know if you think it is needed.
I also changed a line in test_factorization to assert the corr. coef. when the non-linear model is run is higher than when the linear model is run.
It should be almost ready. You can ask Dr. Meyer for a review.

2021-08-16 17:52 UTC, Farnazmdi approved these changes

2021-08-16 20:41 UTC, AshlynPowell commented
@aarmey Could you review this branch for merging? It has the linear model file added, the linear option added to the imputation function and a repeatImputation function that calculates the average correlation coefficient after running the imputation function 20 times.

2021-08-16 21:20 UTC, aarmey requested changes

2021-08-16 21:20 UTC, aarmey commented on de/factorization.py
> +import random
Don't need this.

2021-08-16 21:20 UTC, aarmey commented on de/tests/test_factorization.py
> +    non_lin = ma.corrcoef(ma.masked_invalid(full_X.flatten()), ma.masked_invalid(test_X.flatten()))[0][1]
Tests should check cases we can be absolutely sure will always be true. I'm not sure about that here.

2021-08-16 21:20 UTC, aarmey commented on de/linearModel.py
> +def runFitting(data, U=None, max_iter=300000):
Probably want an option here to pass in the regularization strength, as we'll want to adjust that in the future.

2021-08-17 17:02 UTC, aarmey approved these changes
Looks good.

2021-08-17 17:05 UTC, merged